### ISSUE TITLE
image_prompts.py – borders crop not working properly

### ISSUE THREAD

**Issue by DenisSergeevitch** [sberbank-ai/ru-dalle#22]
From an official documentation:

> borders (dict[str] | int): borders that we croped from pil_image
> example: {'up': 4, 'right': 0, 'left': 0, 'down': 0} (1 int eq 8 pixels)

Up crop works just fine. But if I will pass as a crop argument something other than "Up" in the result, I will get an _AssertionError_:
![telegram-cloud-photo-size-2-5197407051389712641-y](https://user-images.githubusercontent.com/2140110/140338962-41b0b5af-d575-47b2-abce-6fe69ad5fd45.jpg)

Thank you for a fantastic algo ✨

**Comment by shonenkov** [comment]
yes, thank you, we will fix it as soon as possible

**Comment by oriBetelgeuse** [comment]
problem solved: https://github.com/sberbank-ai/ru-dalle/pull/38/files
look at new version 0.0.1rc6
