### ISSUE TITLE
Auto cut pictures into separated images

### ISSUE THREAD

**Issue by Sidiusz** [sberbank-ai/ru-dalle#23]
Есть ли какие-нибудь параметры, которые автоматически нарежут и сохранят сгенерированные картинки по отдельности?
_____
Are there any args that will automatically cut and save separated images?

**Comment by shonenkov** [comment]
hello! thank you for feedback. We will add this feature in method "show" in next version

**Comment by Sidiusz** [comment]
> hello! thank you for feedback. We will add this feature in method "show" in next version

Thanks!

**Comment by nerdyrodent** [comment]
Awesome. Was just looking into doing that XD

**Comment by shonenkov** [comment]
added `save_dir` param for method show in version 0.0.1rc5
