### ISSUE TITLE
Can you make cpu device readme please?

### ISSUE THREAD

**Issue by httpnotonly** [sberbank-ai/ru-dalle#26]
I use macbook air m1 and want to run this repo, but can not do it on 'cuda' device

**Comment by shonenkov** [comment]
I use iMac with M1 for local developing this repo, you can see [tests](https://github.com/sberbank-ai/ru-dalle/blob/master/tests/conftest.py) and [run ci](https://gitlab.com/shonenkov/ru-dalle/-/pipelines) with examples usage on CPU :) 

```python
model = get_rudalle_model('small', pretrained=False, fp16=False, device='cpu')
```


but I don't recommend to run generation without GPU! 
I recommend to use free version of colab or kaggle: 
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1wGE-046et27oHvNlBNPH07qrEQNE04PQ?usp=sharing) [![Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://www.kaggle.com/shonenkov/rudalle-example-generation)
