### ISSUE TITLE
Hosted inference API at Hugging Face issue

### ISSUE THREAD

**Issue by denzenin** [sberbank-ai/ru-dalle#32]
Wanted to test out your model at Hugging Face but got the following

![image](https://user-images.githubusercontent.com/3757759/140559372-43a43f0b-1cf5-4bfe-88e4-e67fb0c76873.png)

Do you guys plan to support deployed API endpoint there or anywhere else?

PS: demos at https://rudalle.ru/ are very entertaining, thanks for you work, guys :)

**Comment by shonenkov** [comment]
Thank you! I really appreciate it :) 

Yes, hosted huggingface spaces project was overloaded such as all our demos. Now huggingface space works again, you can try it [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue)](https://huggingface.co/spaces/anton-l/rudall-e)

I recommend to use colab with stable version of generation) [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1wGE-046et27oHvNlBNPH07qrEQNE04PQ?usp=sharing)
