### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by bitcoin5000** [sberbank-ai/ru-dalle#33]
i use default code and get error after generation 100%
please help i use windows and conda

`◼️ Malevich is 1.3 billion params model from the family GPT3-like, that uses Russian language and text+image multi-modality.
x4 --> ready
tokenizer --> ready
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
vae --> ready
ruclip --> ready
100%|██████████████████████████████████████████████████████████████████████████████| 1024/1024 [00:46<00:00, 22.14it/s]
Traceback (most recent call last):
  File "gen.py", line 29, in <module>
    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=top_k, images_num=images_num, top_p=top_p)
  File "C:\Users\1\anaconda3\lib\site-packages\rudalle\pipelines.py", line 60, in generate_images
    images = vae.decode(codebooks)
  File "C:\Users\1\anaconda3\lib\site-packages\rudalle\vae\model.py", line 38, in decode
    img = self.model.decode(z)
  File "C:\Users\1\anaconda3\lib\site-packages\rudalle\vae\model.py", line 98, in decode
    quant = self.post_quant_conv(quant)
  File "C:\Users\1\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\1\anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\1\anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([3, 256, 32, 32], dtype=torch.float, device='cuda', requires_grad=True).to(memory_format=torch.channels_last)
net = torch.nn.Conv2d(256, 256, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float().to(memory_format=torch.channels_last)
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = true
    allow_tf32 = true
input: TensorDescriptor 0000020481F094B0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 3, 256, 32, 32,
    strideA = 262144, 1, 8192, 256,
output: TensorDescriptor 0000020481F09590
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 3, 256, 32, 32,
    strideA = 262144, 1, 8192, 256,
weight: FilterDescriptor 000001FFD2E76AF0
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NHWC
    nbDims = 4
    dimA = 256, 256, 1, 1,
Pointer addresses:
    input: 0000001538C7D000
    output: 000000153B87D000
    weight: 00000014D3BB0000
`

**Comment by bitcoin5000** [comment]
problem in generate myltiple images i use code for gen 1 image and its working, how to fix?

`from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
from rudalle.utils import seed_everything

# prepare models
device = 'cuda'
dalle = get_rudalle_model('Malevich', pretrained=True, fp16=True, device=device)
realesrgan = get_realesrgan('x4', device=device)
tokenizer = get_tokenizer()
vae = get_vae().to(device)
ruclip, ruclip_processor = get_ruclip('ruclip-vit-base-patch32-v5')
ruclip = ruclip.to(device)

text = 'бабка убила волка'

seed_everything(42)
pil_images = []
scores = []
for top_k, top_p, images_num in [(128, 0.95, 1)]:

    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=top_k, images_num=images_num, top_p=top_p)
    pil_images += _pil_images
    scores += _scores

show(pil_images, 6)`

**Comment by shonenkov** [comment]
@bitcoin5000, how much memory does your GPU have?

**Comment by bitcoin5000** [comment]
> memory

24 gb rtx 3090

**Comment by shonenkov** [comment]
interesting… I have the same device, I will try to reproduce your error 🙏 

Did you use code from readme?

**Comment by bitcoin5000** [comment]
> interesting… I have the same device, I will try to reproduce your error 🙏
> 
> Did you use code from readme?

yes i use this code

`from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
from rudalle.utils import seed_everything

# prepare models
device = 'cuda'
dalle = get_rudalle_model('Malevich', pretrained=True, fp16=True, device=device)
realesrgan = get_realesrgan('x4', device=device)
tokenizer = get_tokenizer()
vae = get_vae().to(device)
ruclip, ruclip_processor = get_ruclip('ruclip-vit-base-patch32-v5')
ruclip = ruclip.to(device)

text = 'изображение радуги на фоне ночного города'

seed_everything(42)
pil_images = []
scores = []
for top_k, top_p, images_num in [
    (2048, 0.995, 3),
    (1536, 0.99, 3),
    (1024, 0.99, 3),
    (1024, 0.98, 3),
    (512, 0.97, 3),
    (384, 0.96, 3),
    (256, 0.95, 3),
    (128, 0.95, 3), 
]:
    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=top_k, images_num=images_num, top_p=top_p)
    pil_images += _pil_images
    scores += _scores

show(pil_images, 6)`

**Comment by shonenkov** [comment]
@bitcoin5000 I run code on RTX3090. But I cant reproduce you error :(

please, check that your GPU memory is empty, also check torch and cuda versions. 
I attach jupyter file with generation [RTX3090.ipynb.zip](https://github.com/sberbank-ai/ru-dalle/files/7490351/RTX3090.ipynb.zip)

in jupyter I also printed versions:

```python
import multiprocessing
import torch
from psutil import virtual_memory

ram_gb = round(virtual_memory().total / 1024**3, 1)

print('CPU:', multiprocessing.cpu_count())
print('RAM GB:', ram_gb)
print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("cuDNN version:", torch.backends.cudnn.version())
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device.type)

!nvidia-smi
>>>
CPU: 32
RAM GB: 125.7
PyTorch version: 1.9.0+cu111
CUDA version: 11.1
cuDNN version: 8005
device: cuda
Sat Nov  6 14:26:59 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:04:00.0 Off |                  N/A |
|  0%   36C    P8    28W / 350W |    162MiB / 24260MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

Please, let me know if you reach success

**Comment by bitcoin5000** [comment]
> @bitcoin5000 I run code on RTX3090. But I cant reproduce you error :(
> 
> please, check that your GPU memory is empty, also check torch and cuda versions. I attach jupyter file with generation [RTX3090.ipynb.zip](https://github.com/sberbank-ai/ru-dalle/files/7490351/RTX3090.ipynb.zip)
> 
> in jupyter I also printed versions:
> 
> ```python
> import multiprocessing
> import torch
> from psutil import virtual_memory
> 
> ram_gb = round(virtual_memory().total / 1024**3, 1)
> 
> print('CPU:', multiprocessing.cpu_count())
> print('RAM GB:', ram_gb)
> print("PyTorch version:", torch.__version__)
> print("CUDA version:", torch.version.cuda)
> print("cuDNN version:", torch.backends.cudnn.version())
> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> print("device:", device.type)
> 
> !nvidia-smi
> >>>
> CPU: 32
> RAM GB: 125.7
> PyTorch version: 1.9.0+cu111
> CUDA version: 11.1
> cuDNN version: 8005
> device: cuda
> Sat Nov  6 14:26:59 2021       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 3090    Off  | 00000000:04:00.0 Off |                  N/A |
> |  0%   36C    P8    28W / 350W |    162MiB / 24260MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> +-----------------------------------------------------------------------------+
> ```
> 
> Please, let me know if you reach success

its working on jupiter but not work in command line
