### ISSUE TITLE
how to make better resolution and save images?

### ISSUE THREAD

**Issue by bitcoin5000** [sberbank-ai/ru-dalle#35]
I dont undestand how to make better resolution or save directly? why command show([pil_image for pil_image, score in sorted(zip(pil_images, scores), key=lambda x: -x[1])] , 6)  show pictrues so small ? and if i  use 
top_images, clip_scores = cherry_pick_by_clip(pil_images, text, ruclip, ruclip_processor, device=device, count=1)
show(top_images, 3)
there will be full resolution? how to make all generated photos in full ress or how to save them directly to file?

**Comment by shonenkov** [comment]
for making `super-resolution` and saving images to directory you can use this code in version `0.0.1rc5`:

```python
sr_images = super_resolution(top_images, realesrgan)
show(sr_images, 3, save_dir='my_images')
```
