### ISSUE TITLE
Im trying create loop to generate pictures how to set random seed?

### ISSUE THREAD

**Issue by bitcoin5000** [sberbank-ai/ru-dalle#36]
What best way to generate infinity pictures and save them? i try create loop but cant set seed to random, random python function not random at all. Please help

**Comment by shonenkov** [comment]
@bitcoin5000 you can choice seed using datetime

```python
from datetime import datetime
seed = int((datetime.utcnow().timestamp() * 10**6) % (2**32-1))
```

now your seed will be new every call `generate_images`  ;)
