### ISSUE TITLE
What top_k, top_p parameters mean?

### ISSUE THREAD

**Issue by korfer** [sberbank-ai/ru-dalle#41]
Good evening! 
What do top_k, top_p parameters mean in:
```
for top_k, top_p, images_num in [
    (2048, 0.995, 3),
    (1536, 0.99, 3)
```
And what 'score' parameter shows?

**Comment by shonenkov** [comment]
@korfer Good afternoon!

information about top_k, top_p filtering you can find [here](https://github.com/huggingface/transformers/blob/master/src/transformers/generation_utils.py#L2553)

`score` shows sum of softmax probs for chosen generated codebooks
