### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by alekseishaklov** [sberbank-ai/ru-dalle#48]
![Снимок экрана от 2021-11-09 22-00-15](https://user-images.githubusercontent.com/78877882/140988256-a214aab8-82bf-46b2-a702-dee56b33c827.png)
![](https://img.rudalle.ru/images/b6/ef/1e/b6ef1e526006441399bcf160888ce932_00000.jpg)
![](https://img.rudalle.ru/images/2a/f4/5d/2af45d9075114d8ab637d773e3efe0a3_00000.jpg)
![](https://img.rudalle.ru/images/b5/ea/ae/b5eaae720dc74e89bc98cc52acf9aba8_00000.jpg)
![](https://img.rudalle.ru/images/16/92/45/169245cbd30c4b9191960daa848ff798_00000.jpg)

Hello! I have tested your neuronet and reached this results. They are so good!

But no kidding, it's a good idea.

**Comment by shonenkov** [comment]
thank you a lot for brilliant feedback @alekseishaklov ! 

in demo used only one (!!!) generative image. It is only for reducing the queue. 
I suppose you own python skills, you can try to make better generative images using colab with more attempts (also see [here](https://openai.com/blog/dall-e/), opeanai generated 512!)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1wGE-046et27oHvNlBNPH07qrEQNE04PQ?usp=sharing)


if you would like to share pictures without any suggestions for improving code, you should use instagram, you can tag our official page ;)
[![](https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white)](https://instagram.com/rudalle.official)
