### ISSUE TITLE
Problem about the PyTorch vision?

### ISSUE THREAD

**Issue by Wang-xd1899** [sberbank-ai/ru-dalle#69]
I have look for the issues but I can't find the same problem. So sorry to bother you.
GPU:
<img width="559" alt="截屏2021-12-02 下午6 35 14" src="https://user-images.githubusercontent.com/44627574/144405693-975b6700-3a2d-4cd9-bcfc-e01028124b43.png">
my python environment: pytorch=1.8.0&torchvision=0.9.0, cudatoolkit=11.3.1&cudnn =8.2.1. I have tried the rudalle=0.3.0 just following the readme.md, or 0.0.1rc5  by the RTX3090.ipynb, but I only got the following error!
<img width="1122" alt="截屏2021-12-02 下午6 38 49" src="https://user-images.githubusercontent.com/44627574/144406209-147b6af5-55d6-4707-bc2f-e46b01fc777b.png">

So I wanna know if any problem in my environment? Waiting for your reply!

**Comment by shonenkov** [comment]
@Wang-xd1899 could you try to set `mlp_activation="gelu"`?

```python
get_rudalle_model('Malevich', pretrained=True, fp16=True, device=device, mlp_activation='gelu')
```

**Comment by Wang-xd1899** [comment]
Surprisingly, after set `mlp_activation="gelu"`, it works! Thank you very much!!!
