### ISSUE TITLE
Commercial Use?

### ISSUE THREAD

**Issue by Anshul58** [sberbank-ai/ru-dalle#81]
Fabulous work! Can we use your code and models for commercial purposes?

**Comment by shonenkov** [comment]
@Anshul58 yes, sure :)

if you mention the name ruDALL-E in your commercial idea, it will be wonderful :)
but it is not necessary with [our License](https://github.com/sberbank-ai/ru-dalle/blob/master/LICENSE.txt)

**Comment by Anshul58** [comment]
Thanks !
