### ISSUE TITLE
The error in ruDall-e code that published in Kaggle

### ISSUE THREAD

**Issue by XieBaoshi** [sberbank-ai/ru-dalle#9]
Execution of ruDall-e code in the Kaggle notebook (as is published), in GPU session ends with error:

```
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_29/1914141142.py in <module>
----> 1 from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
      2 from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
      3 from rudalle.utils import seed_everything

ModuleNotFoundError: No module named 'rudalle'

```

The error message refers to this code:

```
!pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html > /dev/null
!pip install rudalle==0.0.1rc1 > /dev/null
```

**Comment by shonenkov** [comment]
thanks a lot for your feedback! 

I added "commit-version", that run from start to end in GPU session. 
You can try to use this version, don't forget turn on Internet and GPU :)

https://www.kaggle.com/shonenkov/rudalle-example-generation?scriptVersionId=78648155

**Comment by shonenkov** [comment]
let me know if it helps for you

**Comment by XieBaoshi** [comment]
Thank you, now it works with no errors.
After a commit 24 images was generated in two hours, and 6 of these was upscaled. Nice work, I think this is the best text-to-image generator so far :)
