### ISSUE TITLE
"Small" model weights can`t be downloaded

### ISSUE THREAD

**Issue by kinivi** [sberbank-ai/ru-dalle#96]
`get_rudalle_model('small', pretrained=True, fp16=True, device=device)`

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co//resolve/main

<img width="666" alt="Screenshot 2022-01-09 at 20 01 31" src="https://user-images.githubusercontent.com/13486777/148696733-1d745920-5431-402a-9901-22cc9f793cee.png">

Where can be found this weights?

**Comment by minimaxir** [comment]
The `small` model weights were never release.

Additionally, as of `1.0.0`, the `small` flag has been renamed to `dummy`: https://github.com/sberbank-ai/ru-dalle/commit/c3365140ca86d6906a4019064831925e3b99331a#diff-79e3524065df916cdcb092c30d7f65a5cddc4d5d5d0ed73a9c7157fd83c0b711
