### ISSUE TITLE
getting error now , stop working please help

### ISSUE THREAD

**Issue by bitcoin5000** [sberbank-ai/ru-dalle#98]
Stop working after upgrade, what problem ?
after 
`from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
from rudalle.utils import seed_everything`
error:

`ImportError                               Traceback (most recent call last)
<ipython-input-2-30dcdb70f380> in <module>
----> 1 from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
      2 from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
      3 from rudalle.utils import seed_everything

ImportError: cannot import name 'cherry_pick_by_clip' from 'rudalle.pipelines' (C:\Users\u\anaconda3\lib\site-packages\rudalle\pipelines.py)

device = 'cuda'`

**Comment by FrostyDeluxe** [comment]
I'm getting the same error. Did you figure out a solution?
